user:
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  max_name: 50
  max_email: 255
  min_password: 6
edit:
  link: "https://gravatar.com/emails"
department:
  max_name: 50
report:
  max_length: 510
reports:
  report:
    format_date: "%d/%m/%Y"
    max_length: 100
  new:
    datetime: "%d/%m/%Y"
form:
  create_form:
    num_row: 5
users_helper:
  gravatar_size: 50
page_10: 10
page_7: 7
page_5: 5
page_6: 6
digit_50: 50
infor:
  datetime: "%d/%m/%Y"
